### ISSUE TITLE
test på defaultCodeSpace på attributtnivå savnes - gjelder script realiserbarGMLformat50

### ISSUE THREAD

**Issue by mKarge1** [kartverket/UML-modelleringsskript#17]
Det har vært flere tilfeller der det ble oppdaget manglende koblinger til eksterne kodelister. Dette skjedde gjerne når man prøvde å implementere innholdet i GML-skjemafilene. Konkret gjelder dette manglende tagged values "defaultCodeSpace" på attributtnivå. Det er der Shapechange prøver å finne informasjonen. I modellene er gjerne informasjonen på plass i tilknyttede kodelister (tagged value codeList), men det påvirker tilsynelatende ikke Shapechange og dermed ikke resulterende GML-skjemafil.

Dette bør med fordel kunne oppdages tidligere i prosessen da det bl. a. påvirker innhold i underliggende modell og dermed i tilhørende standard/produktspesifikasjon samt endringsbehov i selve GML-skjemafil.

Det bør vurderes å implementere følgende i scriptet "realiserbarGMLformat50":
Hvis det finnes en eller flere kodelister uten innhold og/eller med tagged value codeList samt tagged value asDictionary = true, så skal alle attributter sjekkes der disse kodelistene brukes som type. Attributtene bør ha tagged value defaultCodeSpace med URL til en ekstern kodeliste. Er det ikke tilfellet må brukeren få minimum en advarsel (ev. en feilmelding).

**Comment by KentJonsrud** [comment]
Den nye versjon 0.7 har implementert flere tester fra standarden SOSI Realisering av GML-format versjon 5.0.
