### ISSUE TITLE
listAdocFraModell:  Output i UTF-16 LE BOM i stedet for UTF-8

### ISSUE THREAD

**Issue by aatjora** [kartverket/UML-modelleringsskript#29]
Melding fra Geir Myhr Øien:  
Når jeg kjører scriptet listAdocFraModell i EA blir det generert en fil med UTF-16 LE BOM encoding. Denne encodingen liker ikke helt min tekstbehandler (extension). Gjør jeg om encodingen til UTF-8 fungerer det bra. Noen spesielt grunn til at scriptet bruker UTF-16 i stedet for UTF-8? Trodde 8 var standard.

**Comment by aatjora** [comment]
Satte dette som "bug", siden vi gjerne vil at output skal være i UTF-8.  

Ser ut som koden bruker FileSystemObject.CreateTextFile som har valget mellom "ascii" og "unicode" der sistnevnte ser ut itl å være utf-16.

**Comment by josteinAmlien** [comment]
Problemet ser ut til å være avgrensa til de tilfellene der koden ikke er kopiert dirkete fra github til EA, men via en editor. 
Noen ganger kan en teksteditor, f.eks Notepad+, komme i skade for å endre encoding.
